### ISSUE TITLE
"Bowser.getParser is not a function" on v2.5.1

### ISSUE THREAD

**Issue by goto1** [bowser-js/bowser#339]
Hi!

First of all, thank you for this great package. Appreciate all the work that goes into maintaining this project.

I've noticed after upgrading to `v2.5.1` the following issue:
```js
// throws an error saying "Browser.getParser is not a function"
const browser = Bowser.getParser(userAgent)
```

However, `v2.4.0` seems to works with no issues.

My environment:
- `macOS v10.14.5`
- `node v10.16.0`

Here's a reproducible example that breaks:
- https://repl.it/@devflag/FavoriteBelovedOperation 

Please let me know if there's any other information that's needed.

Thank you!

**Comment by lancedikson** [comment]
Hi, @goto1. Thanks for the heads-up. The bug has been fixed with `2.5.2` release. Please, check it out. Sorry for any inconvenience.

**Comment by goto1** [comment]
Great, thanks!

Just updated to `v2.5.2` and everything is back to normal.

Enjoy the rest of your week!

**Comment by markmcdowell** [comment]
@lancedikson I seem to be getting the exact same issue with v2.6.1, helmet-csp has just updated and i get the same error.

**Comment by artushin** [comment]
@lancedikson I'm seeing this same issue. Looks like there was a recent build. Another build failure similar to https://github.com/lancedikson/bowser/commit/1d613f6227774440420b3fdba4875886e8e5f2c8 ?

**Comment by lancedikson** [comment]
Oh, crap. Thanks, @artushin! Will release a hotfix in a minute.

**Comment by lancedikson** [comment]
2.8.1 should be working properly. Thanks for a heads-up!

**Comment by mschipperheyn** [comment]
Seeing this on 2.8.1
```
Bowser.getParser is not a function
    TypeError: Bowser.getParser is not a function
        at csp (webpack-internal:///../../node_modules/helmet-csp/dist/index.js:34:34)
        at Layer.handle [as handle_request] (webpack-internal:///../../node_modules/express/lib/router/layer.js:95:5)
```

**Comment by dagda1** [comment]
I am seeing this in 2.9.0

**Comment by samkessaram** [comment]
@lancedikson Just checking in. Not sure if you're aware this is still an issue.

**Comment by holtwick** [comment]
I still get this error when using vite + mediasoupclient: https://github.com/versatica/mediasoup-client/issues/159

**Comment by amiraine** [comment]
I'm having this issue.
Mac: 10.15.7
Node: 14.16.1
Bowser: 2.11.0

Let me know if you need additional info.

**Comment by sir-captainmorgan21** [comment]
@lancedikson I am still getting this error with 2.110. Node version 16 and typescript version 4.5.4

**Comment by alyonium** [comment]
Have the same problem

**Comment by EthanSK** [comment]
same issue

**Comment by rismirnov** [comment]
Hi everyone! Try this solution:
https://github.com/helmetjs/csp/issues/96#issuecomment-589949588
